In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("diabetes_data_uncleaned.csv")
print(df.head())

   user_id        date     weight      height  blood_glucose  \
0      1.0  2021-01-01  77.450712  183.993554     112.992869
1      2.0  2021-01-02  67.926035  179.246337     134.219253
2      3.0  2021-01-03  79.715328  170.596304     108.303203
3      4.0  2021-01-04  92.845448  163.530632     127.681539
4      5.0  2021-01-05  66.487699  176.982233      70.000000

   physical_activity  diet  medication_adherence  stress_level  sleep_hours  \
0           0.000000   1.0                   0.0           1.0     6.342317
1          12.792300   0.0                   1.0           2.0    10.658122
2          21.727889   1.0                   1.0           0.0     5.997832
3          67.753753   1.0                   0.0           1.0     7.958814
4          41.131062   1.0                   1.0           0.0     6.774707

   hydration_level   bmi  risk_score
0              1.0  22.9   38.000000
1              1.0  21.1   39.162310
2              1.0  27.4   31.481633
3              1.0  34.7   45.000000
4              1.0  21.2    4.717234

In [6]:
df.shape

(1005, 13)

In [7]:
df.describe()

,user_id,weight,height,blood_glucose,physical_activity,diet,medication_adherence,stress_level,sleep_hours,hydration_level,bmi,risk_score
count,975.000000,975.000000,975.000000,975.000000,975.000000,975.000000,975.000000,975.000000,975.000000,975.000000,975.00000,975.000000
mean,499.693333,70.403957,170.761232,140.803168,30.174902,0.597949,0.698462,0.938462,7.070239,0.709744,24.37641,36.393192
std,289.038236,14.460003,9.757260,38.241614,19.300069,0.490564,0.459161,0.833283,1.885688,0.454114,5.83611,14.934364
min,1.000000,40.000000,150.000000,70.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,11.50000,0.000000
25%,250.500000,60.233178,163.903524,114.004217,15.081934,0.000000,0.000000,0.000000,5.696198,0.000000,20.15000,25.632085
50%,499.000000,70.403288,170.570131,140.021118,29.778160,1.000000,1.000000,1.000000,6.998787,1.000000,24.10000,36.094954
75%,747.500000,79.722988,177.337589,166.503398,43.014651,1.000000,1.000000,2.000000,8.374266,1.000000,28.20000,46.485142
max,1000.000000,120.000000,200.000000,297.049508,94.861859,1.000000,1.000000,2.000000,12.000000,1.000000,45.20000,78.745396

In [8]:
df.isnull()

,user_id,date,weight,height,blood_glucose,physical_activity,diet,medication_adherence,stress_level,sleep_hours,hydration_level,bmi,risk_score
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,False,False,False,False,False,False,False,False,False,False,False,False,False
1001,False,False,False,False,False,False,False,False,False,False,False,False,False
1002,False,False,False,False,False,False,False,False,False,False,False,False,False
1003,False,False,False,False,False,False,False,False,False,False,False,False,False
1004,False,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
df.isnull().sum()

user_id                 30
date                     1
weight                  30
height                  30
blood_glucose           30
physical_activity       30
diet                    30
medication_adherence    30
stress_level            30
sleep_hours             30
hydration_level         30
bmi                     30
risk_score              30
dtype: int64